name: 'scoring-deploy-1'

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SC_SSH_HOST_1 }}
          username: ${{ secrets.SC_SSH_USERNAME_1 }}
          password: ${{ secrets.SC_SSH_PASSWORD_1 }}
          port: ${{ secrets.SC_SSH_PORT }}
          script: |
            cd ~/web12-MOJ
            git pull
            ./deploy-scoring-server.sh
